// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode
//create three variable email ,@ ,.
//set email in 1 variable with text write your email
//set @ in 2 variable with text and find first occurrence of text
//set . in 3 variable with text and find last occurrence of text
//set id do and else for printing invalid and valid email
// paste your JS generated by blockly below here
var email, _, _2;


email = window.prompt('your email');
_ = email.indexOf('@') + 1;
_2 = email.lastIndexOf('.') + 1;
if (_ == 0) {
  window.alert('invalid');
} else if (_2 < _) {
  window.alert('invalid');
} else if (_ < _2) {
  window.alert('valid');
}