// Rewrite the instructions in your own words
/*first the program should ask a phrase for the user the
// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here
var acronym, anyString, i;


acronym = '';
anyString = window.prompt('Enter your text').split(' ');
for (var i_index in anyString) {
  i = anyString[i_index];
  acronym += String(i.charAt(0));
}
window.alert(acronym.toUpperCase());